import type { IRoutineBlock } from "./types";

export const ROUTINE_BLOCKS_MOCK: IRoutineBlock[] = [
  {
    id: "1",
    title: "Algoritmos y Estructuras",
    description: "Clase teórica",
    location: "Aula 201",
    color: "blue",
    dayOfWeek: 0,
    startHour: 9,
    startMinute: 0,
    endHour: 11,
    endMinute: 0,
  },
  {
    id: "2",
    title: "Gimnasio",
    description: "Rutina de fuerza",
    location: "Gym Central",
    color: "green",
    dayOfWeek: 0,
    startHour: 7,
    startMinute: 0,
    endHour: 8,
    endMinute: 30,
  },
  {
    id: "3",
    title: "Diseño UX",
    description: "Taller práctico",
    location: "Lab 3",
    color: "purple",
    dayOfWeek: 1,
    startHour: 14,
    startMinute: 0,
    endHour: 16,
    endMinute: 0,
  },
  {
    id: "4",
    title: "Gimnasio",
    description: "Rutina de fuerza",
    location: "Gym Central",
    color: "green",
    dayOfWeek: 2,
    startHour: 7,
    startMinute: 0,
    endHour: 8,
    endMinute: 30,
  },
  {
    id: "5",
    title: "Base de Datos",
    description: "Práctica de SQL",
    location: "Sala Info",
    color: "orange",
    dayOfWeek: 2,
    startHour: 10,
    startMinute: 0,
    endHour: 12,
    endMinute: 0,
  },
  {
    id: "6",
    title: "Algoritmos y Estructuras",
    description: "Clase teórica",
    location: "Aula 201",
    color: "blue",
    dayOfWeek: 3,
    startHour: 9,
    startMinute: 0,
    endHour: 11,
    endMinute: 0,
  },
  {
    id: "7",
    title: "Gimnasio",
    description: "Rutina de fuerza",
    location: "Gym Central",
    color: "green",
    dayOfWeek: 4,
    startHour: 7,
    startMinute: 0,
    endHour: 8,
    endMinute: 30,
  },
  {
    id: "8",
    title: "Tenis",
    description: "Clase con profe",
    location: "Club Náutico",
    color: "yellow",
    dayOfWeek: 5,
    startHour: 9,
    startMinute: 0,
    endHour: 10,
    endMinute: 30,
  },
];
